export const movies = [
  {
    title: "Adams Family",
    year: "2019",
    genre: "Animation",
    director: "Greg Tiernan",
    actor: "Oscar Isaac",
    cover: "./images/film/film_cover_adams-family.webp",
    description:
      "The eccentrically macabre family moves to a bland suburb where Wednesday Addams' friendship with the daughter of a hostile and conformist local reality show host exacerbates conflict between the families.",
    token: "0",
  },
  {
    title: "Batman",
    year: "2022",
    genre: "Action",
    director: "Matt Reeves",
    actor: "Robert Pattinson",
    cover: "./images/film/film_cover_the-batman.webp",
    fallbackCover: "./images/film/film_cover_the-batman.jpg",
    description:
      "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
    token: "1",
  },
  {
    title: "Godzilla: King of the Monsters",
    year: "2019",
    genre: "Adventure",
    director: "ichael Dougherty",
    actor: "Kyle Chandler",
    cover: "./images/film/film_cover_godzilla.webp",
    fallbackCover: "./images/film/film_cover_godzilla.jpg",
    description:
      "The crypto-zoological agency Monarch faces off against a battery of god-sized monsters, including the mighty Godzilla, who collides with Mothra, Rodan, and his ultimate nemesis, the three-headed King Ghidorah.",
    token: "2",
  },
  {
    title: "Fast & Furious Presents: Hobbs & Shaw",
    year: "2019",
    genre: "Action",
    director: "David Leitch",
    actor: "Dwayne Johnson, Jason Statham",
    cover: "./images/film/film_cover_hobbs-and-shaw.webp",
    fallbackCover: "./images/film/film_cover_hobbs-and-shaw.jpg",
    description:
      "Lawman Luke Hobbs and outcast Deckard Shaw form an unlikely alliance when a cyber-genetically enhanced villain threatens the future of humanity.",
    token: "3",
  },
  {
    title: "Once Upon A time in Hollywood",
    year: "2019",
    genre: "Drama",
    director: "Quentin Tarantino",
    actor: "Leonardo DiCaprio",
    cover: "./images/film/film_cover_once_upon_a_time.webp",
    fallbackCover: "./images/film/film_cover_once_upon_a_time.jpg",
    description:
      "A faded television actor and his stunt double strive to achieve fame and success in the final years of Hollywood's Golden Age in 1969 Los Angeles.",
    token: "4",
  },
  {
    title: "Scream",
    year: "2022",
    genre: "Horror",
    director: "Matt bettinelli-Olpin",
    actor: "Neve Campbell",
    cover: "./images/film/film_cover_scream.webp",
    fallbackCover: "./images/film/film_cover_scream.jpg",
    description:
      "25 years after a streak of brutal murders shocked the quiet town of Woodsboro, Calif., a new killer dons the Ghostface mask and begins targeting a group of teenagers to resurrect secrets from the town's deadly past.",
    token: "5",
  },
  {
    title: "Sweetheart",
    year: "2019",
    genre: "Adventure",
    director: "J.D. Dillard",
    actor: "Kiersey Clemons",
    cover: "./images/film/film_cover_sweetheart.webp",
    fallbackCover: "./images/film/film_cover_sweetheart.jpg",
    description:
      "Jenn has washed ashore a small tropical island and it doesn't take her long to realize she's completely alone. She must spend her days not only surviving the elements, but must also fend off the malevolent force that comes out each night.",
    token: "6",
  },
  {
    title: "Toy Story 4",
    year: "2019",
    genre: "Animation",
    director: "Josh Cooley",
    actor: "Tom Hanks",
    cover: "./images/film/film_cover_toy-story-4.webp",
    fallbackCover: "./images/film/film_cover_toy-story-4.jpg",
    description:
      "When a new toy called Forky joins Woody and the gang, a road trip alongside old and new friends reveals how big the world can be for a toy.",
    token: "7",
  },
];
